-- MySQL Script generated by MySQL Workbench
-- 04/06/17 19:20:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema recipedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recipedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recipedb` DEFAULT CHARACTER SET utf8 ;
USE `recipedb` ;

-- -----------------------------------------------------
-- Table `recipedb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`users` (
  `id` INT NOT NULL DEFAULT 0,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipedb`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`recipes` (
  `id` INT NOT NULL DEFAULT 0,
  `recipe_name` VARCHAR(120) NOT NULL,
  `permissions` VARCHAR(45) NOT NULL,
  `rank` FLOAT NOT NULL,
  `num_ratings` INT NOT NULL,
  `users_id` INT NOT NULL,
  `recipe_image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipes_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_recipes_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `recipedb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipedb`.`favoriteRecipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`favoriteRecipes` (
  `id` INT NOT NULL DEFAULT 0,
  `users_id` INT NOT NULL,
  `recipes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_favoriteRecipes_users1_idx` (`users_id` ASC),
  INDEX `fk_favoriteRecipes_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_favoriteRecipes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `recipedb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoriteRecipes_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `recipedb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipedb`.`sharedRecipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`sharedRecipes` (
  `id` INT NOT NULL DEFAULT 0,
  `users_id` INT NOT NULL,
  `recipes_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_sharedRecipes_users1_idx` (`users_id` ASC),
  INDEX `fk_sharedRecipes_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_sharedRecipes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `recipedb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sharedRecipes_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `recipedb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipedb`.`friendsList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`friendsList` (
  `id` INT NOT NULL DEFAULT 0,
  `users_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_friendsList_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_friendsList_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `recipedb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipedb`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`ingredients` (
  `id` INT NOT NULL DEFAULT 0,
  `recipes_id` INT NOT NULL,
  `ingredient` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ingredients_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_ingredients_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `recipedb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipedb`.`instructions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`instructions` (
  `id` INT NOT NULL DEFAULT 0,
  `recipes_id` INT NOT NULL,
  `instruction_number` INT NOT NULL,
  `instruction` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_instructions_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_instructions_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `recipedb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipedb`.`friendRequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipedb`.`friendRequests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_friendRequests_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_friendRequests_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `recipedb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
